[tool.poetry]
name = "iicategen"
version = "1.0.0"
description = "A Catalogue Entry Generator for interesting images."
authors = ["hysrx"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
hentai = "^3.1.3"
iiprintingpress = "*"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
